# Generated by Django 5.0 on 2023-12-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summoner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puuid", models.CharField(max_length=200, unique=True)),
                ("game_name", models.CharField(max_length=32)),
                ("tag_line", models.CharField(max_length=5)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
