# Generated by Django 5.0 on 2023-12-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("summoners", "0002_summoner_account_id_summoner_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LadderStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_id", models.CharField(max_length=400)),
                ("queue_type", models.CharField(max_length=69)),
                ("tier", models.CharField(max_length=40)),
                ("rank", models.CharField(max_length=3)),
                ("lp", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("veteran", models.BooleanField()),
                ("fresh_blood", models.BooleanField()),
                ("inactive", models.BooleanField()),
                ("hot_streak", models.BooleanField()),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "belongs_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="summoners.summoner",
                    ),
                ),
            ],
        ),
    ]
